output   = "internal/dbmodels"
no-tests = "true"
no-hooks = "true"
wipe = "true"
pkgname = "dbmodels"

[psql]
host="localhost"
sslmode="disable"
dbname = "todo"
user = "postgres"
pass = "omsairam"
[auto-columns]