// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	Tags     string
	TaskTags string
	Tasks    string
	TodoList string
	Users    string
}{
	Tags:     "tags",
	TaskTags: "task_tags",
	Tasks:    "tasks",
	TodoList: "todo_list",
	Users:    "users",
}
